repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: cargo-format
        name: Cargo format
        entry: cargo fmt
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: Cargo clippy
        entry: cargo clippy -- --deny warnings
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-check
        name: Cargo check
        entry: cargo check
        language: system
        files: \.rs$
        pass_filenames: false