[package]
name = "imgsize"
version = "0.1.0"
edition = "2021"

[lib]
name = "imgsize"
crate-type = ["cdylib", "lib"]

[[bin]]
name = "imgsize"

[dependencies]
byteorder = "1.5.0"
pyo3 = "0.19.0"

[dev-dependencies]
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
